import {
  AtomIcon,
  BinaryIcon,
  BookOpenIcon,
  BracesIcon,
  BrainIcon,
  BriefcaseIcon,
  CalculatorIcon,
  ChartLineIcon,
  CodeIcon,
  CogIcon,
  CoinsIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  DnaIcon,
  DumbbellIcon,
  EarthIcon,
  FlaskConicalIcon,
  GamepadIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeartPulseIcon,
  InfinityIcon,
  LandmarkIcon,
  LanguagesIcon,
  LayersIcon,
  LeafIcon,
  LibraryIcon,
  LightbulbIcon,
  LockIcon,
  type LucideIcon,
  MapIcon,
  MicroscopeIcon,
  MonitorIcon,
  MusicIcon,
  NetworkIcon,
  PaletteIcon,
  PenToolIcon,
  PiIcon,
  RocketIcon,
  ScaleIcon,
  ServerIcon,
  ShieldIcon,
  SigmaIcon,
  SmartphoneIcon,
  TerminalIcon,
  UsersIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";

/** Curated icon set for subjects. The key is stored in the database. */
export const SUBJECT_ICONS: { key: string; label: string; icon: LucideIcon }[] =
  [
    { key: "book", label: "Книга", icon: BookOpenIcon },
    { key: "code", label: "Код", icon: CodeIcon },
    { key: "braces", label: "Скобки", icon: BracesIcon },
    { key: "terminal", label: "Терминал", icon: TerminalIcon },
    { key: "binary", label: "Двоичный код", icon: BinaryIcon },
    { key: "cpu", label: "Процессор", icon: CpuIcon },
    { key: "database", label: "База данных", icon: DatabaseIcon },
    { key: "server", label: "Сервер", icon: ServerIcon },
    { key: "network", label: "Сеть", icon: NetworkIcon },
    { key: "globe", label: "Веб", icon: GlobeIcon },
    { key: "monitor", label: "Монитор", icon: MonitorIcon },
    { key: "smartphone", label: "Смартфон", icon: SmartphoneIcon },
    { key: "lock", label: "Безопасность", icon: LockIcon },
    { key: "shield", label: "Защита", icon: ShieldIcon },
    { key: "sigma", label: "Сумма", icon: SigmaIcon },
    { key: "pi", label: "Пи", icon: PiIcon },
    { key: "infinity", label: "Бесконечность", icon: InfinityIcon },
    { key: "calculator", label: "Калькулятор", icon: CalculatorIcon },
    { key: "chart", label: "График", icon: ChartLineIcon },
    { key: "atom", label: "Атом", icon: AtomIcon },
    { key: "flask", label: "Колба", icon: FlaskConicalIcon },
    { key: "microscope", label: "Микроскоп", icon: MicroscopeIcon },
    { key: "dna", label: "ДНК", icon: DnaIcon },
    { key: "leaf", label: "Лист", icon: LeafIcon },
    { key: "earth", label: "Земля", icon: EarthIcon },
    { key: "compass", label: "Компас", icon: CompassIcon },
    { key: "map", label: "Карта", icon: MapIcon },
    { key: "brain", label: "Мозг", icon: BrainIcon },
    { key: "lightbulb", label: "Идея", icon: LightbulbIcon },
    { key: "languages", label: "Языки", icon: LanguagesIcon },
    { key: "library", label: "Библиотека", icon: LibraryIcon },
    { key: "graduation", label: "Диплом", icon: GraduationCapIcon },
    { key: "landmark", label: "Здание", icon: LandmarkIcon },
    { key: "scale", label: "Весы", icon: ScaleIcon },
    { key: "briefcase", label: "Портфель", icon: BriefcaseIcon },
    { key: "coins", label: "Монеты", icon: CoinsIcon },
    { key: "users", label: "Люди", icon: UsersIcon },
    { key: "heart", label: "Здоровье", icon: HeartPulseIcon },
    { key: "dumbbell", label: "Спорт", icon: DumbbellIcon },
    { key: "palette", label: "Палитра", icon: PaletteIcon },
    { key: "pen", label: "Перо", icon: PenToolIcon },
    { key: "music", label: "Музыка", icon: MusicIcon },
    { key: "gamepad", label: "Игры", icon: GamepadIcon },
    { key: "layers", label: "Слои", icon: LayersIcon },
    { key: "cog", label: "Шестерёнка", icon: CogIcon },
    { key: "wrench", label: "Ключ", icon: WrenchIcon },
    { key: "zap", label: "Молния", icon: ZapIcon },
    { key: "rocket", label: "Ракета", icon: RocketIcon },
  ];

const BY_KEY = new Map(SUBJECT_ICONS.map((i) => [i.key, i.icon]));

/** Lucide component for a stored icon key; falls back to a book. */
export function subjectIcon(key: string | undefined | null): LucideIcon {
  return (key && BY_KEY.get(key)) || BookOpenIcon;
}
