/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    /** Проверка живости */
    get: operations["healthz"];
  };
  "/settings": {
    /** Настройки сайта, текущая неделя и навигация */
    get: operations["getSettings"];
  };
  "/home": {
    /**
     * Сводка для главной страницы
     * @description Ближайшие и просроченные дедлайны лаб, события и сдачи, свежие конспекты, предметы.
     */
    get: operations["getHome"];
  };
  "/subjects": {
    /**
     * Список предметов
     * @description Предметы в порядке `position` со счётчиками опубликованных лаб, конспектов и квизов.
     */
    get: operations["listSubjects"];
  };
  "/subjects/{slug}": {
    /** Предмет с его лабами, конспектами и квизами */
    get: operations["getSubject"];
  };
  "/labs": {
    /**
     * Список лабораторных
     * @description Опубликованные лабы всех предметов или одного предмета. Длинные MDX-поля (`content`, `requirements`, `submission`, `variants`) в списке пустые.
     */
    get: operations["listLabs"];
  };
  "/labs/{subject}/{slug}": {
    /** Лабораторная целиком */
    get: operations["getLab"];
  };
  "/calendar": {
    /**
     * Календарь за период
     * @description Дедлайны лабораторных, события (контрольные, экзамены, консультации) и сдачи.
     * Поле `source` различает `lab`, `event` и `practice`. Без параметров возвращает окно от месяца назад до полугода вперёд.
     * `from` и `to` принимают RFC 3339 или дату `YYYY-MM-DD` (дата в `to` включает весь день).
     * Некорректное значение молча заменяется значением по умолчанию.
     */
    get: operations["getCalendar"];
  };
  "/calendar.ics": {
    /**
     * iCalendar-фид календаря
     * @description Подписка для Google Calendar, Apple Calendar и Outlook: дедлайны лаб, события и сдачи. Окно: два месяца назад и год вперёд.
     * У дедлайнов, контрольных и экзаменов напоминание за сутки. Ответ кэшируется на 15 минут.
     */
    get: operations["getCalendarICS"];
  };
  "/notes": {
    /**
     * Список конспектов
     * @description Опубликованные конспекты, по всем предметам или по одному. Поле `content` в списке пустое.
     */
    get: operations["listNotes"];
  };
  "/notes/{subject}/{slug}": {
    /**
     * Конспект целиком
     * @description Вместе с привязанными квизами и соседними конспектами предмета для навигации.
     */
    get: operations["getNote"];
  };
  "/quizzes": {
    /** Список квизов */
    get: operations["listQuizzes"];
  };
  "/quizzes/{slug}": {
    /**
     * Квиз с вопросами
     * @description Формат вопросов описан в `docs/quiz-format.md`. Правильные ответы включены, проверка выполняется на клиенте.
     */
    get: operations["getQuiz"];
  };
  "/faq": {
    /** Частые вопросы */
    get: operations["listFAQ"];
  };
  "/pages": {
    /** Статические страницы */
    get: operations["listPages"];
  };
  "/pages/{slug}": {
    /** Статическая страница */
    get: operations["getPage"];
  };
  "/search": {
    /**
     * Поиск по опубликованному
     * @description Полнотекстовый поиск по лабам, конспектам, квизам, ЧаВо, страницам и предметам.
     * Русский словарь с учётом словоформ, последнее слово ищется по префиксу (поиск по мере набора),
     * опечатки ловятся триграммами. Результаты отсортированы по релевантности: совпадение в заголовке
     * весит больше, чем в тексте. Пустой запрос и запрос без букв и цифр дают пустой список.
     */
    get: operations["search"];
  };
  "/practice": {
    /**
     * Занятия для сдачи лаб
     * @description По умолчанию только будущие. Для анонимных запросов `participants`, `myLabIds` и `availableLabs` пустые,
     * `signedIn` равно `false`; вошедшие студенты видят участников и могут записаться (см. `docs/api.md`).
     */
    get: operations["listPractice"];
  };
  "/practice/{id}": {
    /** Одно занятие */
    get: operations["getPractice"];
  };
  "/comments/{target}/{id}": {
    /**
     * Комментарии к конспекту, лабе или посту
     * @description Читать может кто угодно. `POST` с тем же путём и телом `{ body }` требует студенческую куку `edu_user`,
     * `DELETE /comments/{id}` удаляет свой комментарий. Конспект или лаба должны быть опубликованы.
     */
    get: operations["listComments"];
  };
  "/posts": {
    /**
     * Лента постов
     * @description Пользовательские посты одной ленты. `POST /posts` с `PostInput` создаёт пост от имени студента,
     * `PUT`/`DELETE /posts/{id}` меняют и удаляют свой пост, `PUT`/`DELETE /posts/{id}/like` ставят и снимают лайк.
     * Поля `liked` и `mine` считаются для студента, если передана кука `edu_user`.
     * Без куки отдаются только посты с `visibility: public`: `members` видят лишь вошедшие студенты,
     * и посты с `nsfw: true` всегда `members`. Комментарии к скрытому посту анонимам тоже недоступны (404).
     */
    get: operations["listPosts"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Формат всех ошибок API */
    Error: {
      /** @description Сообщение для пользователя */
      error: string;
      /** @enum {string} */
      code:
        | "validation"
        | "not_found"
        | "conflict"
        | "unauthorized"
        | "bad_password"
        | "rate_limited"
        | "internal";
      /** @description Ошибки валидации по полям (только для `validation`) */
      fields?: {
        [key: string]: string;
      };
    };
    /**
     * Format: date-time
     * @description RFC 3339 с таймзоной
     */
    DateTime: string;
    /**
     * Format: date
     * @description `YYYY-MM-DD`
     */
    Date: string;
    /** @enum {string} */
    Parity: "odd" | "even";
    /**
     * @description В публичных ответах всегда `published`
     * @enum {string}
     */
    Status: "draft" | "published";
    /** @enum {string} */
    SubjectColor:
      | "blue"
      | "indigo"
      | "violet"
      | "cyan"
      | "teal"
      | "emerald"
      | "amber"
      | "orange"
      | "rose"
      | "slate";
    Link: {
      title: string;
      /** Format: uri */
      url: string;
    };
    Settings: {
      siteTitle: string;
      groupName: string;
      description: string;
      semesterStart: components["schemas"]["Date"] | null;
      semesterEnd: components["schemas"]["Date"] | null;
      firstWeekParity: components["schemas"]["Parity"];
      timezone: string;
      links: components["schemas"]["Link"][];
      /** @description В публичных ответах всегда пустая строка */
      inviteCode: string;
      updatedAt: components["schemas"]["DateTime"];
    };
    /** @description Текущая учебная неделя, считается от начала семестра */
    Week: {
      /** @description Номер недели; 0, если семестр не настроен */
      number: number;
      parity: components["schemas"]["Parity"];
      start: components["schemas"]["DateTime"];
      /** @description Сейчас идёт семестр */
      inRange: boolean;
      /** @description Дата начала семестра задана */
      configured: boolean;
    };
    AuthInfo: {
      /** @description Username бота; пусто, если вход через Telegram не настроен */
      telegramBot: string;
      telegramBotId: string;
      /** @description Доступен вход по имени (только вне production) */
      devLogin: boolean;
      /** @description Для первого входа нужен код доступа */
      inviteRequired: boolean;
    };
    SubjectRef: {
      id: number;
      slug: string;
      name: string;
      shortName: string;
      color: components["schemas"]["SubjectColor"];
      /** @description Ключ иконки; пусто = иконка по умолчанию */
      icon: string;
    };
    Subject: components["schemas"]["SubjectRef"] & {
      teacher: string;
      /** @description MDX */
      description: string;
      links: components["schemas"]["Link"][];
      position: number;
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
    };
    SubjectWithCounts: components["schemas"]["Subject"] & {
      labsCount: number;
      notesCount: number;
      quizzesCount: number;
    };
    /** @description Денормализованные поля предмета у дочерних сущностей */
    SubjectJoin: {
      subjectSlug: string;
      subjectName: string;
      subjectShortName: string;
      subjectColor: components["schemas"]["SubjectColor"] | "";
      subjectIcon: string;
    };
    Lab: components["schemas"]["SubjectJoin"] & {
      id: number;
      subjectId: number;
      /** @description Ноль допустим для необязательной вводной лабы */
      number: number;
      slug: string;
      title: string;
      summary: string;
      /** @description Задание, MDX */
      content: string;
      /** @description Требования, MDX */
      requirements: string;
      /** @description Как сдавать, MDX */
      submission: string;
      /** @description Варианты, MDX */
      variants: string;
      materials: components["schemas"]["Link"][];
      deadlineAt: components["schemas"]["DateTime"] | null;
      deadlineNote: string;
      maxScore: number | null;
      teacher: string;
      status: components["schemas"]["Status"];
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
    };
    Note: components["schemas"]["SubjectJoin"] & {
      id: number;
      subjectId: number;
      number: number;
      slug: string;
      title: string;
      summary: string;
      /** @description MDX с формулами и кодом */
      content: string;
      lectureDate: components["schemas"]["Date"] | null;
      status: components["schemas"]["Status"];
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
      /** @description Опубликованные квизы, привязанные к конспекту */
      quizzesCount: number;
    };
    NoteResponse: components["schemas"]["Note"] & {
      quizzes: components["schemas"]["QuizSummary"][];
      prev: components["schemas"]["Note"] | null;
      next: components["schemas"]["Note"] | null;
    };
    QuizOption: {
      id: string;
      /** @description Markdown */
      text: string;
      correct: boolean;
    };
    QuizQuestion: {
      id: string;
      /** @enum {string} */
      type: "single" | "multiple" | "text";
      /** @description Markdown с формулами */
      prompt: string;
      /** @description Для `single` и `multiple` */
      options?: components["schemas"]["QuizOption"][];
      /** @description Принимаемые ответы для `text`, сравнение без учёта регистра, пробелов и ё/е */
      answers?: string[];
      /** @description Показывается после ответа */
      explanation?: string;
      /** @default 1 */
      points?: number;
      tags?: string[];
    };
    Quiz: components["schemas"]["SubjectJoin"] & {
      id: number;
      subjectId: number | null;
      noteId: number | null;
      slug: string;
      title: string;
      description: string;
      questions: components["schemas"]["QuizQuestion"][];
      shuffleQuestions: boolean;
      shuffleOptions: boolean;
      status: components["schemas"]["Status"];
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
      noteSlug: string;
      noteTitle: string;
    };
    QuizSummary: components["schemas"]["Quiz"] & {
      questionsCount: number;
    };
    FAQItem: {
      id: number;
      question: string;
      /** @description MDX */
      answer: string;
      category: string;
      position: number;
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
    };
    Page: {
      id: number;
      slug: string;
      title: string;
      summary: string;
      /** @description MDX */
      content: string;
      position: number;
      /** @description Показывать в меню сайта */
      showInNav: boolean;
      status: components["schemas"]["Status"];
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
    };
    CalendarItem: {
      id: string;
      /** @enum {string} */
      source: "lab" | "event" | "practice";
      /** @enum {string} */
      kind:
        | "deadline"
        | "test"
        | "exam"
        | "consultation"
        | "other"
        | "practice";
      title: string;
      startsAt: components["schemas"]["DateTime"];
      endsAt: components["schemas"]["DateTime"] | null;
      allDay: boolean;
      location: string;
      description: string;
      /** @description Путь на сайте, например `/labs/prog/lab-1` */
      path: string;
      /** @description Внешняя ссылка события, если есть */
      url: string;
      subject: components["schemas"]["SubjectRef"] | null;
      /** @description Только для `source: lab` */
      labNumber?: number;
      /** @description Только для `source: lab` */
      labId?: number;
    };
    SearchResult: {
      /** @enum {string} */
      kind: "lab" | "note" | "quiz" | "faq" | "page" | "subject";
      title: string;
      subtitle: string;
      /** @description Путь на сайте */
      path: string;
      /** @description Фрагмент текста, совпадения обёрнуты в <mark>; может быть пустым */
      snippet: string;
    };
    SettingsResponse: {
      settings: components["schemas"]["Settings"];
      week: components["schemas"]["Week"];
      now: components["schemas"]["DateTime"];
      /** @description Страницы с `showInNav`, без `content` */
      navPages: components["schemas"]["Page"][];
      auth: components["schemas"]["AuthInfo"];
    };
    HomeResponse: {
      settings: components["schemas"]["Settings"];
      week: components["schemas"]["Week"];
      now: components["schemas"]["DateTime"];
      /** @description Только дедлайны лаб */
      upcomingDeadlines: components["schemas"]["CalendarItem"][];
      overdueDeadlines: components["schemas"]["CalendarItem"][];
      /** @description Контрольные, экзамены, консультации и сдачи */
      upcomingEvents: components["schemas"]["CalendarItem"][];
      recentNotes: components["schemas"]["Note"][];
      subjects: components["schemas"]["SubjectWithCounts"][];
    };
    SubjectResponse: {
      subject: components["schemas"]["Subject"];
      labs: components["schemas"]["Lab"][];
      notes: components["schemas"]["Note"][];
      quizzes: components["schemas"]["QuizSummary"][];
    };
    CalendarResponse: {
      items: components["schemas"]["CalendarItem"][];
      from: components["schemas"]["DateTime"];
      to: components["schemas"]["DateTime"];
      now: components["schemas"]["DateTime"];
    };
    PublicUser: {
      id: number;
      name: string;
      photoUrl: string;
    };
    LabRef: {
      id: number;
      number: number;
      title: string;
      slug: string;
      subjectSlug: string;
    };
    Participant: {
      user: components["schemas"]["PublicUser"];
      labs: components["schemas"]["LabRef"][];
    };
    PracticeSession: components["schemas"]["SubjectJoin"] & {
      id: number;
      subjectId: number;
      startsAt: components["schemas"]["DateTime"];
      endsAt: components["schemas"]["DateTime"] | null;
      location: string;
      /** @description `null` = без ограничения */
      capacity: number | null;
      note: string;
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
      /** @description Число записавшихся студентов */
      signupsCount: number;
    };
    PracticeSessionView: components["schemas"]["PracticeSession"] & {
      /** @description Только для вошедших студентов, иначе пусто */
      participants: components["schemas"]["Participant"][];
      myLabIds: number[];
      /** @description Мест нет */
      full: boolean;
      /** @description Занятие уже прошло */
      past: boolean;
      /** @description Опубликованные лабы предмета, только для вошедших */
      availableLabs: components["schemas"]["LabRef"][];
    };
    PracticeListResponse: {
      sessions: components["schemas"]["PracticeSessionView"][];
      now: components["schemas"]["DateTime"];
      signedIn: boolean;
    };
    Comment: {
      id: number;
      /** @enum {string} */
      targetType: "note" | "lab" | "post";
      targetId: number;
      body: string;
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
      authorId: number;
      authorName: string;
      authorPhotoUrl: string;
      /** @description Комментарий текущего студента */
      mine: boolean;
    };
    Post: {
      id: number;
      /** @enum {string} */
      kind: "shawarma" | "joke";
      /** @description Название точки для шавермы */
      title: string;
      body: string;
      address: string;
      /** @description Цена в рублях */
      price: number | null;
      rating: number | null;
      /**
       * @description `members` — только для вошедших студентов
       * @enum {string}
       */
      visibility: "public" | "members";
      /** @description Пометка 18+; сайт размывает текст до подтверждения возраста */
      nsfw: boolean;
      createdAt: components["schemas"]["DateTime"];
      updatedAt: components["schemas"]["DateTime"];
      authorId: number;
      authorName: string;
      authorPhotoUrl: string;
      likesCount: number;
      commentsCount: number;
      liked: boolean;
      mine: boolean;
    };
    PostInput: {
      /**
       * @description Задаётся при создании
       * @enum {string}
       */
      kind: "shawarma" | "joke";
      title?: string;
      body: string;
      address?: string;
      price?: number | null;
      /** @description Обязательна для шавермы */
      rating?: number | null;
      /**
       * @default public
       * @enum {string}
       */
      visibility?: "public" | "members";
      /**
       * @description При true видимость принудительно становится members
       * @default false
       */
      nsfw?: boolean;
    };
  };
  responses: {
    /** @description Некорректный запрос или превышен лимит; формат ошибки одинаковый для всех кодов */
    ClientError: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Не найдено или не опубликовано */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Слаг, сгенерированный из названия транслитерацией */
    Slug: string;
    /** @description Слаг предмета */
    SubjectSlug: string;
    /** @description Слаг предмета для фильтрации */
    SubjectFilter?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Проверка живости */
  healthz: {
    responses: {
      /** @description Сервис работает */
      200: {
        content: {
          "application/json": {
            /** @constant */
            status: "ok";
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Настройки сайта, текущая неделя и навигация */
  getSettings: {
    responses: {
      /** @description Настройки */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Сводка для главной страницы
   * @description Ближайшие и просроченные дедлайны лаб, события и сдачи, свежие конспекты, предметы.
   */
  getHome: {
    responses: {
      /** @description Сводка */
      200: {
        content: {
          "application/json": components["schemas"]["HomeResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Список предметов
   * @description Предметы в порядке `position` со счётчиками опубликованных лаб, конспектов и квизов.
   */
  listSubjects: {
    responses: {
      /** @description Предметы */
      200: {
        content: {
          "application/json": components["schemas"]["SubjectWithCounts"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Предмет с его лабами, конспектами и квизами */
  getSubject: {
    parameters: {
      path: {
        slug: components["parameters"]["Slug"];
      };
    };
    responses: {
      /** @description Предмет */
      200: {
        content: {
          "application/json": components["schemas"]["SubjectResponse"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Список лабораторных
   * @description Опубликованные лабы всех предметов или одного предмета. Длинные MDX-поля (`content`, `requirements`, `submission`, `variants`) в списке пустые.
   */
  listLabs: {
    parameters: {
      query?: {
        subject?: components["parameters"]["SubjectFilter"];
      };
    };
    responses: {
      /** @description Лабы */
      200: {
        content: {
          "application/json": components["schemas"]["Lab"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Лабораторная целиком */
  getLab: {
    parameters: {
      path: {
        subject: components["parameters"]["SubjectSlug"];
        slug: components["parameters"]["Slug"];
      };
    };
    responses: {
      /** @description Лаба */
      200: {
        content: {
          "application/json": components["schemas"]["Lab"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Календарь за период
   * @description Дедлайны лабораторных, события (контрольные, экзамены, консультации) и сдачи.
   * Поле `source` различает `lab`, `event` и `practice`. Без параметров возвращает окно от месяца назад до полугода вперёд.
   * `from` и `to` принимают RFC 3339 или дату `YYYY-MM-DD` (дата в `to` включает весь день).
   * Некорректное значение молча заменяется значением по умолчанию.
   */
  getCalendar: {
    parameters: {
      query?: {
        /** @description Начало периода */
        from?: string;
        /** @description Конец периода */
        to?: string;
        subject?: components["parameters"]["SubjectFilter"];
      };
    };
    responses: {
      /** @description Элементы календаря */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * iCalendar-фид календаря
   * @description Подписка для Google Calendar, Apple Calendar и Outlook: дедлайны лаб, события и сдачи. Окно: два месяца назад и год вперёд.
   * У дедлайнов, контрольных и экзаменов напоминание за сутки. Ответ кэшируется на 15 минут.
   */
  getCalendarICS: {
    parameters: {
      query?: {
        subject?: components["parameters"]["SubjectFilter"];
      };
    };
    responses: {
      /** @description Файл календаря */
      200: {
        headers: {
          "Content-Disposition"?: string;
          "Cache-Control"?: string;
        };
        content: {
          "text/calendar": string;
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Список конспектов
   * @description Опубликованные конспекты, по всем предметам или по одному. Поле `content` в списке пустое.
   */
  listNotes: {
    parameters: {
      query?: {
        subject?: components["parameters"]["SubjectFilter"];
      };
    };
    responses: {
      /** @description Конспекты */
      200: {
        content: {
          "application/json": components["schemas"]["Note"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Конспект целиком
   * @description Вместе с привязанными квизами и соседними конспектами предмета для навигации.
   */
  getNote: {
    parameters: {
      path: {
        subject: components["parameters"]["SubjectSlug"];
        slug: components["parameters"]["Slug"];
      };
    };
    responses: {
      /** @description Конспект */
      200: {
        content: {
          "application/json": components["schemas"]["NoteResponse"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /** Список квизов */
  listQuizzes: {
    parameters: {
      query?: {
        subject?: components["parameters"]["SubjectFilter"];
      };
    };
    responses: {
      /** @description Квизы */
      200: {
        content: {
          "application/json": components["schemas"]["QuizSummary"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Квиз с вопросами
   * @description Формат вопросов описан в `docs/quiz-format.md`. Правильные ответы включены, проверка выполняется на клиенте.
   */
  getQuiz: {
    parameters: {
      path: {
        slug: components["parameters"]["Slug"];
      };
    };
    responses: {
      /** @description Квиз */
      200: {
        content: {
          "application/json": components["schemas"]["Quiz"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /** Частые вопросы */
  listFAQ: {
    responses: {
      /** @description Вопросы в порядке `position` */
      200: {
        content: {
          "application/json": components["schemas"]["FAQItem"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Статические страницы */
  listPages: {
    responses: {
      /** @description Опубликованные страницы, `content` в списке пустой */
      200: {
        content: {
          "application/json": components["schemas"]["Page"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Статическая страница */
  getPage: {
    parameters: {
      path: {
        slug: components["parameters"]["Slug"];
      };
    };
    responses: {
      /** @description Страница */
      200: {
        content: {
          "application/json": components["schemas"]["Page"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Поиск по опубликованному
   * @description Полнотекстовый поиск по лабам, конспектам, квизам, ЧаВо, страницам и предметам.
   * Русский словарь с учётом словоформ, последнее слово ищется по префиксу (поиск по мере набора),
   * опечатки ловятся триграммами. Результаты отсортированы по релевантности: совпадение в заголовке
   * весит больше, чем в тексте. Пустой запрос и запрос без букв и цифр дают пустой список.
   */
  search: {
    parameters: {
      query: {
        q: string;
        /** @description Значения вне диапазона заменяются на 20 */
        limit?: number;
      };
    };
    responses: {
      /** @description Результаты */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /**
   * Занятия для сдачи лаб
   * @description По умолчанию только будущие. Для анонимных запросов `participants`, `myLabIds` и `availableLabs` пустые,
   * `signedIn` равно `false`; вошедшие студенты видят участников и могут записаться (см. `docs/api.md`).
   */
  listPractice: {
    parameters: {
      query?: {
        subject?: components["parameters"]["SubjectFilter"];
        /** @description Любое непустое значение включает прошедшие занятия */
        past?: string;
      };
    };
    responses: {
      /** @description Занятия */
      200: {
        content: {
          "application/json": components["schemas"]["PracticeListResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  /** Одно занятие */
  getPractice: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Занятие */
      200: {
        content: {
          "application/json": components["schemas"]["PracticeSessionView"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Комментарии к конспекту, лабе или посту
   * @description Читать может кто угодно. `POST` с тем же путём и телом `{ body }` требует студенческую куку `edu_user`,
   * `DELETE /comments/{id}` удаляет свой комментарий. Конспект или лаба должны быть опубликованы.
   */
  listComments: {
    parameters: {
      path: {
        target: "note" | "lab" | "post";
        id: number;
      };
    };
    responses: {
      /** @description Комментарии, старые первыми */
      200: {
        content: {
          "application/json": components["schemas"]["Comment"][];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Лента постов
   * @description Пользовательские посты одной ленты. `POST /posts` с `PostInput` создаёт пост от имени студента,
   * `PUT`/`DELETE /posts/{id}` меняют и удаляют свой пост, `PUT`/`DELETE /posts/{id}/like` ставят и снимают лайк.
   * Поля `liked` и `mine` считаются для студента, если передана кука `edu_user`.
   * Без куки отдаются только посты с `visibility: public`: `members` видят лишь вошедшие студенты,
   * и посты с `nsfw: true` всегда `members`. Комментарии к скрытому посту анонимам тоже недоступны (404).
   */
  listPosts: {
    parameters: {
      query: {
        kind: "shawarma" | "joke";
        /** @description `top` — сначала посты с наибольшим числом лайков */
        sort?: "new" | "top";
      };
    };
    responses: {
      /** @description Посты */
      200: {
        content: {
          "application/json": components["schemas"]["Post"][];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
}
